# set these pinned workspaces
workspace = r[1-4], persistent:1

# pin those default windows into specific workspaces
windowrulev2 = workspace 1, class:(kitty)
windowrulev2 = workspace 2, class:(firefox)
windowrulev2 = workspace 3, class:(discord)
